// src/services/mockProducts.ts
import type { Product } from '../types/Product';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Arroz Parboilizado Tipo 1 (5kg)',
    description: 'Arroz branco, parboilizado e de alta qualidade, pacote de 5kg.',
    price: 25.50,
    quantity: 150,
    imageUrl: 'https://placehold.co/300x200.png?text=Arroz',
    category: 'Mercearia',
    expirationDate: '2027-10-15',
  },
  {
    id: 2,
    name: 'Óleo de Soja (900ml)',
    description: 'Óleo de soja refinado, ideal para frituras e preparos.',
    price: 7.99,
    quantity: 80,
    imageUrl: 'https://placehold.co/300x200.png?text=Óleo',
    category: 'Mercearia',
    expirationDate: '2026-08-20',
  },
  {
    id: 3,
    name: 'Leite Integral UHT (1L)',
    description: 'Leite de vaca integral, longa vida.',
    price: 4.29,
    quantity: 200,
    imageUrl: 'https://placehold.co/300x200.png?text=Leite',
    category: 'Laticínios',
    expirationDate: '2026-07-10',
  },
  {
    id: 4,
    name: 'Detergente Líquido Limão (500ml)',
    description: 'Alto poder desengordurante com fragrância de limão.',
    price: 2.19,
    quantity: 95,
    imageUrl: 'https://placehold.co/300x200.png?text=Detergente',
    category: 'Limpeza',
    expirationDate: '2028-01-01',
  },
  {
    id: 5,
    name: 'Pão de Forma Tradicional (500g)',
    description: 'Pão de forma macio e fresco, ideal para sanduíches.',
    price: 6.50,
    quantity: 40,
    imageUrl: 'https://placehold.co/300x200.png?text=Pão',
    category: 'Padaria',
    expirationDate: '2026-02-20',
  },
    {
    id: 6,
    name: 'Maçã Fuji (Kg)',
    description: 'Maçã Fuji fresca e crocante, vendida por quilo.',
    price: 8.99,
    quantity: 30,
    imageUrl: 'https://placehold.co/300x200.png?text=Maçã',
    category: 'Hortifruti',
    expirationDate: '2026-03-05',
  },
  {
    id: 7,
    name: 'Café Torrado e Moído (500g)',
    description: 'Café tradicional, com torra média e moagem fina.',
    price: 14.90,
    quantity: 0, // Esgotado
    imageUrl: 'https://placehold.co/300x200.png?text=Café',
    category: 'Mercearia',
    expirationDate: '2027-05-22',
  },
];
